POST http://localhost:5001/api/users/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Vbaaa",
    "lastName": "Ivanov",
    "email": "ivanovddd@mwoman.com",
    "password": "1111d",
    "birthday": "1982-01-09",
    "gender": "male"
}